"""single_agent_swarm.py — AutoResearch loop with robustness iteration.
Usage: python single_agent_swarm.py [--rounds N]   (requires ANTHROPIC_API_KEY)

Design decisions:
  1. Robustness as second metric (alongside pass_rate) — rewards defensive coding
  2. GOAL_BINARY / GOAL_UNARY — explicit arity separation in prompt
  3. regenerate_calculator() — calculator.py auto-generated, never agent-touched
  4. MIN_PASS = 0.9 — minimum quality threshold for acceptance
  5. Convergence termination (idle_rounds), not fixed list
  6. Two acceptance paths: new functions (composite score) vs robustness improvements (Δ ≥ 0.05)
  7. Hybrid autonomy: agent prioritizes improvements when robustness < threshold
"""
import ast, json, shutil, subprocess, sys, textwrap, requests, time
from pathlib import Path
from typing import Any

# ── Goal definitions: separated by arity for correct prompt guidance ──────────
GOAL_BINARY = ["add","subtract","multiply","divide","modulo","power"]
GOAL_UNARY  = ["negate","absolute","sqrt","log","sin","cos","tan"]
GOAL        = GOAL_BINARY + GOAL_UNARY

SRC  = Path("core/operations.py")
TEST = Path("tests/test_basic.py")
CALC = Path("core/calculator.py")
EXPS = Path("experiments")

RUNS             = int(sys.argv[sys.argv.index("--rounds")+1]) if "--rounds" in sys.argv else 20
MIN_PASS         = 0.9     # minimum pass_rate to accept any proposal
MAX_IDLE         = 2       # consecutive rounds without improvement before stopping
MIN_ROBUST_DELTA = 0.05    # minimum robustness gain to accept a refinement of existing op
ROBUST_THRESHOLD = 0.7     # below this, agent prioritizes improving existing ops

class OllamaClient:
    def __init__(self, model="qwen2.5:7b"):
        self.model = model
        self.url = "http://localhost:11434/api/generate"
    
    def generate(self, prompt):
        payload = {"model": self.model, "prompt": prompt, "stream": False}
        resp = requests.post(self.url, json=payload, timeout=60)
        return resp.json().get("response")

USE_LOCAL = "--local" in sys.argv

class ProjectMemory:
    def __init__(self, path="memory/failed_patterns.md"):
        self.path = Path(path)
        self.path.parent.mkdir(exist_ok=True)
        if not self.path.exists(): 
            self.path.write_text("# Project Memory\n\nGenerated by basic_agent loop.\n\n", encoding="utf-8")
    
    def add_failure(self, fn, reason, code):
        entry = f"## Failure: {fn} (Cycle {state['cycle']})\n- Reason: {reason}\n- Code Snippet:\n```python\n{code}\n```\n\n"
        with self.path.open("a", encoding="utf-8") as f: f.write(entry)
    
    def get_context(self, max_lines=200):
        # Emulates the 200-line limit of Claude's auto-memory skill
        lines = self.path.read_text(encoding="utf-8").splitlines()
        return "\n".join(lines[-max_lines:])

TOOL = {
    "name": "propose_change",
    "description": "One change per cycle. Both fields must be complete Python files, not snippets.",
    "input_schema": {
        "type": "object",
        "required": ["reasoning","new_file_content","new_test_content","function_name"],
        "properties": {
            "reasoning":        {"type":"string"},
            "new_file_content": {"type":"string", "description":"Complete operations.py"},
            "new_test_content": {"type":"string", "description":"Complete test_basic.py"},
            "function_name":    {"type":"string"},
        },
    },
}

# ── Bootstrap: lets the script run from a clean directory without manual setup ─
def ensure_files() -> None:
    """Exists because the script must be self-contained — no manual file creation needed."""
    for d in ("core","tests"): Path(d).mkdir(exist_ok=True)
    EXPS.mkdir(exist_ok=True)
    if not SRC.exists():
        SRC.write_text(
            "import math\n\n"
            "def add(a, b):\n    return a + b\n\n"
            "def subtract(a, b):\n    return a - b\n",
            encoding="utf-8",
        )
    if not TEST.exists():
        TEST.write_text(
            "import pytest\nfrom core.operations import *\n\n"
            "def test_add():      assert add(1,2) == 3\n"
            "def test_subtract(): assert subtract(5,3) == 2\n",
            encoding="utf-8",
        )
    regenerate_calculator()

# ── Keeps calculator.py in sync with operations.py without agent involvement ──
def regenerate_calculator() -> None:
    """Exists because the agent should only own operations.py — calculator.py is a derived artifact."""
    try:
        tree = ast.parse(SRC.read_text(encoding="utf-8"))
    except (FileNotFoundError, SyntaxError):
        return
    implemented = {n.name for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)}

    sym = {"add":"+","subtract":"-","multiply":"*","divide":"/","modulo":"%","power":"**"}
    binary_entries = "\n".join(
        f'    "{sym[f]}": {f},' for f in GOAL_BINARY if f in implemented and f in sym
    )
    unary_entries = "\n".join(
        f'    "{f}": {f},' for f in GOAL_UNARY if f in implemented
    )
    CALC.write_text(textwrap.dedent(f"""\
        from core.operations import *

        BINARY = {{
        {binary_entries}
        }}
        UNARY = {{
        {unary_entries}
        }}

        def evaluate(expr: str) -> float:
            t = expr.strip().split()
            if len(t) == 3: return BINARY[t[1]](float(t[0]), float(t[2]))
            if len(t) == 2: return UNARY[t[0]](float(t[1]))
            raise ValueError(f"Cannot parse: {{expr!r}}")
    """), encoding="utf-8")

# ── Rewards defensive coding, not just test passage ───────────────────────────
def robustness_score() -> float:
    """Exists because pass_rate alone rewards happy-path code — this incentivizes error guards."""
    try:
        tree = ast.parse(SRC.read_text(encoding="utf-8"))
    except (FileNotFoundError, SyntaxError):
        return 0.0
    guarded = total = 0
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            total += 1
            if any(isinstance(x, (ast.Raise, ast.Try)) for x in ast.walk(node)):
                guarded += 1
    return guarded / total if total else 0.0

# ── Single optimization target that balances correctness and defensiveness ────
def composite_score(rate: float, robust: float, elapsed: float) -> float:
    """Exists because optimizing two metrics independently creates conflicting incentives."""
    perf = 1.0 / (1.0 + elapsed)  # Rewards faster execution
    return 0.6 * rate + 0.2 * robust + 0.2 * perf

# ── Objective function the acceptance logic optimizes against ─────────────────
def run_tests() -> tuple[float, float]:
    """Exists because every proposal needs an objective, automated verdict — no human in the loop."""
    start_time = time.perf_counter()
    report = Path("report.json")
    report.unlink(missing_ok=True)

    subprocess.run(
        ["python", "-m", "pytest", "tests/test_basic.py", "-q", "--tb=no",
         "--json-report", f"--report-file={report}"],
        capture_output=True, timeout=30,
    )
    if report.exists():
        try:
            s = json.loads(report.read_text(encoding="utf-8")).get("summary", {})
            total = s.get("total", 0)
            return s.get("passed", 0) / total if total else 0.0
        except (json.JSONDecodeError, KeyError):
            pass

    out = subprocess.run(
        ["python", "-m", "pytest", "tests/test_basic.py", "-v", "--tb=no", "--no-header"],
        capture_output=True, text=True, timeout=30,
    ).stdout
    ok  = out.count(" PASSED")
    bad = out.count(" FAILED") + out.count(" ERROR")
    rate = ok / (ok + bad) if (ok + bad) else 0.0
    return rate, time.perf_counter() - start_time

# ── Preserves every accepted state for post-hoc analysis and rollback ─────────
def save_snapshot(fn: str, rate: float, robust: float, elapsed: float,
                  change_type: str = "new_function") -> None:
    """Exists because without snapshots, a bad late-stage proposal could erase all progress."""
    snap = EXPS / f"exp_{state['cycle']:03d}"
    snap.mkdir(exist_ok=True)
    shutil.copy(SRC,  snap / SRC.name)
    shutil.copy(TEST, snap / TEST.name)
    (snap / "meta.json").write_text(json.dumps({
        "cycle": state["cycle"], "function": fn,
        "type": change_type,
        "pass_rate": rate, "robustness": robust, "elapsed": elapsed,
        "score": composite_score(rate, robust, elapsed),
        "ops_done": state["ops_done"],
        "improved": state["improved"],
    }, indent=2), encoding="utf-8")

# ── State ─────────────────────────────────────────────────────────────────────
state = {"cycle":0, "score":0.0, "pass_rate":0.0, "robustness":0.0,
         "ops_done":[], "improved":[], "failed":{}}

# ── Translates system state into a structured prompt the model can act on ─────
def ask(client: Any, memory: ProjectMemory) -> dict | None:
    """Exists because the agent needs current context each round — stale prompts produce duplicates."""
    remaining_b = [op for op in GOAL_BINARY if op not in state["ops_done"]]
    remaining_u = [op for op in GOAL_UNARY  if op not in state["ops_done"]]
    improvable  = [op for op in state["ops_done"] if op not in state["improved"]]
    failures    = "\n".join(f"  - {f}: failed {n}x" for f, n in state["failed"].items())

    # Hybrid autonomy: guide the agent based on current robustness level
    if state["robustness"] < ROBUST_THRESHOLD and improvable:
        priority_instruction = textwrap.dedent(f"""\
            PRIORITY: robustness_score is {state['robustness']:.0%}, below threshold {ROBUST_THRESHOLD:.0%}.
            Focus on IMPROVING an existing function from this list by adding error guards:
              {improvable}
            For example: divide should raise ZeroDivisionError, sqrt/log should raise ValueError.
            You may also add a new function if you prefer, but improvements are encouraged.""")
    elif remaining_b or remaining_u:
        priority_instruction = textwrap.dedent(f"""\
            PRIORITY: robustness is adequate ({state['robustness']:.0%}).
            Focus on ADDING a new function from the remaining lists below.""")
    else:
        priority_instruction = textwrap.dedent(f"""\
            All functions are implemented. Focus on IMPROVING robustness of existing functions.
            Improvable (no guards yet): {improvable if improvable else 'all functions already improved'}""")

    prompt = textwrap.dedent(f"""
        You are basic_agent. Add or improve ONE function per cycle.

        Remaining binary ops (two args: a, b) : {remaining_b}
        Remaining unary  ops (one  arg: a)    : {remaining_u}
        Already implemented                   : {state['ops_done']}
        Already improved (have error guards)  : {state['improved']}

        {priority_instruction}

        Rules:
        - Pick ONE op — either new from remaining lists, or existing to improve
        - Binary functions take (a, b); unary functions take (a)
        - Return COMPLETE file contents — not snippets
        - Preserve ALL existing functions and tests
        - Error guards are rewarded: divide/modulo raise ZeroDivisionError when b==0,
          sqrt/log raise ValueError for invalid domain inputs
        - Use pytest.approx for float comparisons
        - Include `import math` at the top of operations.py
        {chr(10)+"Do NOT repeat these failed proposals:"+chr(10)+failures if failures else ""}
        
        {chr(10)+ "IMPORTANT: Return ONLY a JSON object with keys: reasoning, function_name, new_file_content, new_test_content." if USE_LOCAL else ""}

        Current pass rate : {state['pass_rate']:.0%}
        Current robustness: {state['robustness']:.0%}
        Current speed     : {state.get('elapsed', 0):.3f}s
        Current score     : {state['score']:.0%}

        ### PROJECT MEMORY (Learnings from past cycles)
        {memory.get_context()}

        {SRC}:
        ```python
{SRC.read_text(encoding="utf-8")}```

        {TEST}:
        ```python
{TEST.read_text(encoding="utf-8")}```

        {("Return JSON output now." if USE_LOCAL else "Call propose_change now.")}
    """).strip()

    if USE_LOCAL:
        raw = client.generate(prompt)
        try:
            # Basic JSON extraction for local models
            start = raw.find("{")
            end = raw.rfind("}") + 1
            return json.loads(raw[start:end])
        except (ValueError, json.JSONDecodeError):
            print(f"  [ERR] Local model failed to return valid JSON: {raw[:100]}...")
            return None

    import anthropic
    resp = client.messages.create(
        model="claude-sonnet-4-20250514", max_tokens=2500,
        tools=[TOOL], tool_choice={"type":"any"},
        messages=[{"role":"user","content":prompt}],
    )
    blk = next((b for b in resp.content if b.type == "tool_use"), None)
    return dict(blk.input) if blk else None

# ── Orchestrates the feedback loop: propose → test → accept/reject → repeat ──
def main() -> None:
    """Exists because without a central loop, the propose/test/accept cycle has no driver."""
    ensure_files()
    if USE_LOCAL:
        client = OllamaClient()
    else:
        import anthropic
        client = anthropic.Anthropic()
    memory = ProjectMemory()
    idle   = 0
    print(f"single_agent_swarm  rounds={RUNS}  min_pass={MIN_PASS:.0%}  "
          f"idle_limit={MAX_IDLE}  robust_threshold={ROBUST_THRESHOLD:.0%}\n")

    for r in range(1, RUNS + 1):
        proposal = ask(client, memory)
        if not proposal:
            print(f"[{r}] no proposal returned"); idle += 1
        else:
            fn     = proposal.get("function_name","?")
            reason = proposal.get("reasoning","")[:55]
            print(f"[{r}] {fn:12s}  \"{reason}\"", end="  ")

            old_src  = SRC.read_text(encoding="utf-8")
            old_test = TEST.read_text(encoding="utf-8")
            SRC.write_text(proposal["new_file_content"], encoding="utf-8")
            TEST.write_text(proposal["new_test_content"], encoding="utf-8")

            rate, elapsed = run_tests()
            robust = robustness_score()
            score  = composite_score(rate, robust, elapsed)

            is_new = fn not in state["ops_done"]

            if is_new:
                # ── Path A: new function — accept if composite score improves ─
                if score >= state["score"] and rate >= MIN_PASS:
                    state.update(cycle=state["cycle"]+1, score=score,
                                 pass_rate=rate, robustness=robust, elapsed=elapsed)
                    state["ops_done"].append(fn)
                    state["failed"].pop(fn, None)
                    regenerate_calculator()
                    save_snapshot(fn, rate, robust, elapsed, change_type="new_function")
                    idle = 0
                    print(f"ACCEPTED  rate={rate:.0%}  robust={robust:.0%}  score={score:.0%}  time={elapsed:.2f}s")
                else:
                    SRC.write_text(old_src, encoding="utf-8")
                    TEST.write_text(old_test, encoding="utf-8")
                    state["failed"][fn] = state["failed"].get(fn, 0) + 1
                    idle += 1
                    rej = ("below MIN_PASS" if rate < MIN_PASS
                           else "no score improvement")
                    print(f"REJECTED  [{rej}]  rate={rate:.0%}  score={score:.0%}")
                    memory.add_failure(fn, f"Rejection: {rej}", proposal["new_file_content"])
            else:
                # ── Path B: improvement — accept if robustness Δ meets minimum ─
                robust_delta = robust - state["robustness"]
                if rate >= MIN_PASS and robust_delta >= MIN_ROBUST_DELTA:
                    old_robust = state["robustness"]
                    state.update(cycle=state["cycle"]+1, score=score,
                                 pass_rate=rate, robustness=robust, elapsed=elapsed)
                    if fn not in state["improved"]:
                        state["improved"].append(fn)
                    state["failed"].pop(fn, None)
                    regenerate_calculator()
                    save_snapshot(fn, rate, robust, elapsed, change_type="robustness_improvement")
                    idle = 0
                    print(f"IMPROVED  robust={old_robust:.0%}→{robust:.0%}  "
                          f"Δ={robust_delta:+.0%}  rate={rate:.0%}")
                else:
                    SRC.write_text(old_src, encoding="utf-8")
                    TEST.write_text(old_test, encoding="utf-8")
                    state["failed"][fn] = state["failed"].get(fn, 0) + 1
                    idle += 1
                    rej = ("below MIN_PASS" if rate < MIN_PASS
                           else f"robustness Δ={robust_delta:+.2f} < {MIN_ROBUST_DELTA}")
                    print(f"REJECTED  [{rej}]  rate={rate:.0%}  robust={robust:.0%}")

        # Convergence: stop if no progress for MAX_IDLE rounds
        if idle >= MAX_IDLE:
            print(f"\nConverged — {idle} consecutive rounds without improvement.")
            break

    # ── Summary ───────────────────────────────────────────────────────────────
    remaining = [op for op in GOAL if op not in state["ops_done"]]
    print(f"\nops_done    : {state['ops_done']}")
    print(f"improved    : {state['improved']}")
    print(f"remaining   : {remaining}")
    print(f"final score : {state['score']:.0%}  "
          f"(pass={state['pass_rate']:.0%}  robust={state['robustness']:.0%})")
    print(f"cycles      : {state['cycle']}")

    # ── Smoke test: verify calculator.py evaluates real expressions ───────────
    print("\n── calculator.py smoke test ──")
    try:
        import importlib
        if "core.calculator" in sys.modules:
            importlib.reload(sys.modules["core.calculator"])
        from core.calculator import evaluate, BINARY, UNARY

        passed = 0
        if "+" in BINARY:
            result = evaluate("2 + 3")
            assert result == 5.0, f"expected 5.0, got {result}"
            passed += 1
            print(f"  ✓ evaluate('2 + 3') = {result}")
        if UNARY:
            first_unary = next(iter(UNARY))
            result = evaluate(f"{first_unary} 4")
            passed += 1
            print(f"  ✓ evaluate('{first_unary} 4') = {result}")
        if passed == 0:
            print("  ⚠ no operations available to test")
        else:
            print(f"  smoke test PASSED ({passed} expressions evaluated)")
    except Exception as e:
        print(f"  ✗ smoke test FAILED — {e}")


if __name__ == "__main__":
    main()
